# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Flowscripter.flowscripter-io-cli
PackageVersion: 3.0.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: flowscripter-io-cli.exe
Scope: machine
InstallModes:
- silent
UpgradeBehavior: install
ReleaseDate: 2026-10-09
ElevationRequirement: elevationRequired
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/flowscripter/flowscripter-io-cli/releases/download/v3.0.1/flowscripter-io-cli_Windows_x64.zip
  InstallerSha256: D690F725B9F3A282E106915AA9779F75C93D9EFD0612796D66598B5C8AE3E287
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://github.com/flowscripter/flowscripter-io-cli/releases/download/v3.0.1/flowscripter-io-cli_Windows_arm64.zip
  InstallerSha256: 2F69D5C1E73C95CC7284B90F58B14688DA0918E69DE5F49337AD6F9F0367CC07
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
